version: '3.8'

services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 --chdir /home/app/api/project app:shuffle_app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    #
    # PSQL environment variables stored in a file
    # as this is production / storing creds in plaintext is bad
    # however, since you want to see how I work
    # the file is left as a plaintext.
    # As per the development docker-compose, a real production
    # would have that file stored in the container's
    # /run/secrets/blah file
    #
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    ports:
      - 6925:80
    depends_on:
    - api

volumes:
  postgres_data_prod: